model:
    name: "Default Profile"
    width: 10
    height: 10
    seed: null
    messages_path: messages.yaml

agents:
  agent.WSNAgent:
    - id: 0
      x: 0
      y: 0
      color: "black"
      seed: null
      messages:
        - src: 0
          dest: -1
          message_type: "Advertisement"
          data: 0x08
